### ISSUE TITLE
[BUG-Beta]: Set an empty property for header doesn't work

### ISSUE THREAD

**Issue by Lisandra-dev** [noatpad/obsidian-banners#125]
Hello!
I try to manually add the header with adding the property `banner_header: `. But it doesn't show. I always need to use the command, and it's not practical…

Here my frontmatter:
```yaml
---
aliases:
  - 25-08-23
category: Projects/GitHub Publisher
date: 2023-08-25
description: 
share: false
type: 
banner_header: 
---
```

Note: Changing the header for already set heading via the command work. Not in a new file fully manually.

I will prefer to have the header linked to a key, like title or the filename title, without using the frontmatter. Using an option, or, for example : 
```yaml
banner_header: "{{filename}}"
```
for title
and
```yaml
banner_header: {{alias}}
```
for alias

It can be used for any key of the frontmatter using the key name surrounded by brackets (`{{}}`). Moreover, converting the banner_header to a list allow to use multiple key for fallback, ie if for example the key `{{title}}` doesn't exist, use `{{filename}}`:
```yaml
banner_header:
 - {{title}}
 - {{alias}}
 - {{filename}}
```
