### ISSUE TITLE
Incompatibility with Minimal Theme

### ISSUE THREAD

**Issue by Aeases** [noatpad/obsidian-banners#130]

**Comment by noatpad** [comment]
Gonna give this a looksee if this is something that can be resolved within Banners, as well as if it's something to be fixed from the alternative banner placement that I mentioned earlier (#129)

**Comment by RyotaUshio** [comment]
It seems that this part of Minimal's `theme.css` is the problem:

```css
.minimal-line-nums .workspace-leaf-content[data-type=markdown] .is-readable-line-width {
	--file-margins: 1rem 0 0 var(--folding-offset)
}
```

and this `--file-margins` variable is referenced by this part of Banners' `style.css`, which styles the grandparent `div` element of the banner `img`:
```css
.obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
    width: calc(100% + 2 * var(--file-margins));
    margin: calc(-1 * var(--file-margins));
    margin-bottom: var(--file-margins);
}
```

`--file-margins` is `var(--size-4-8) = 32px` in the default theme, so `width: calc(100% + 2 * var(--size-4-8));`can be a quick fix. Of course this may not be a proper solution, but I'm not sure how this should be resolved cuz I don't know much about CSS...
