### ISSUE TITLE
Option to group banner front matter under a single key

### ISSUE THREAD

**Issue by redactedscribe** [noatpad/obsidian-banners#143]
Instead of defining `banner:`, `banner_x:`, `banner_y:`, and so on ungrouped in the YAML, what about an option to group them under a single key? Such as:

```yaml
banner:
  image:
  banner_x:
  banner_y:
  # ...
```

(Keys under `banner:` could drop the `banner_` prefix.)

This would condense the keys into a single line when viewed via Properties, saving some vertical space. It would however also make making edits via Properties not possible (at least in Obsidian <1.4 -- maybe >1.4 supports editing nested YAML via Properties?). Since the banners are typically set and forget, editing the values via the YAML source is fine to me.

Taking the idea further, the `banner:` key which groups the other keys could be arbitrary:

```yaml
banner_plugin:
  image:
  # ...
```

```yaml
some_key:
  obs_banner:
    image:
    # ...
```

Etc.

Thanks.
