### ISSUE TITLE
🚀 CSS that fixes beta to for on Obsidian 1.5

### ISSUE THREAD

**Issue by simonfossom** [noatpad/obsidian-banners#146]
@noatpad I don't quite understand how your code is organized. I never worked in Svelte, but this fixes the problem for me:

```CSS
/* fixes bugs */
.is-mobile .obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
    width: 100%;
    height: calc(var(--banners-mobile-height) - 80px) !important;
    margin: 0;
}

.obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
    width: 100%;
    height: calc(var(--banners-height) - 80px) !important;
}

/* fix top in minimal theme */
.view-content > .markdown-source-view.mod-cm6 > .cm-editor > .cm-scroller {
    padding: 0; 
}

/* suggestion for styling */
.inline-title {
    position: relative;
    z-index: 2;
}
```

![Screenshot 2023-12-28 at 10 45 24](https://github.com/noatpad/obsidian-banners/assets/8134850/c61338be-850b-479a-9b46-6e23dcc25b0a)

**Comment by gvzhang** [comment]
this code work for me in 2.0.5-beta

**Comment by Net-Slayer** [comment]
![image](https://github.com/noatpad/obsidian-banners/assets/14405930/44f797c0-e87a-4fdd-a9bc-89b2ed8b2edc)
Unfortunately this doesn't work on mine, also using the minimal theme and banners 2.0.5-beta

My content is a H2 heading with the date, followed by a H4 heading with navigational backlinks.
Plugin settings at default except for banner height at 200.

**Comment by simonfossom** [comment]
> ![image](https://github.com/noatpad/obsidian-banners/assets/14405930/44f797c0-e87a-4fdd-a9bc-89b2ed8b2edc)
> Unfortunately this doesn't work on mine, also using the minimal theme and banners 2.0.5-beta
> 
> My content is a H2 heading with the date, followed by a H4 heading with navigational backlinks.
> Plugin settings at default except for banner height at 200.
> 

I am also using minimal theme. Why doesn't it work? 🤔

You can adjust this in my snippet.
You can see that I've pushed by `- 80px`. You can add or subtract to that number to adjust where the page content starts.

**Comment by Net-Slayer** [comment]
Thank you I'm making some tweaks now ^^



For reference before Obsidian's update and the new banner beta my banners would look like this:

![LivePreview](https://github.com/noatpad/obsidian-banners/assets/14405930/6b483dc0-03ef-4622-a59e-e728ddf0cc99)

I'm glad your fix works for some people's setups but seems to break in my case.
I'm gonna take a look at what tweaks I can add that hopefully will help others go back to what it was.

**Comment by Net-Slayer** [comment]
### Been doing some digging for my issue:
#### Minimal theme is the culprit:

By default the banner wrapper div has the following css:

```css
.obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
    width: calc(100% + 2 * var(--file-margins));
    margin: calc(-1 * var(--file-margins));
    margin-bottom: var(--file-margins);
```

The default theme sets the following file margins:
```css:
...
--file-margins: 48px
...
```

However, the Minimal theme **breaks this entirely** by setting the following:
(https://github.com/kepano/obsidian-minimal)

```css
/* Minimal/theme.css */
...
--file-margins: var(--size-4-2) var(--size-4-12)
...
```
(This just means use "--size-4-2" 8px for vertical and "--size-4-12" for horizontal)

This breaks many banner calculations as it's not a single value anymore, resulting in a short width banner and an out of place icon/header title as calculations involving --file-margins resolve to zero:
![image](https://github.com/noatpad/obsidian-banners/assets/14405930/cbccc0af-bccb-416d-b35a-544ab238c314)

My solution is the following css snippet that just overrides the banner plugins's use of --file-margins with the appropriate sizes from the minimal theme.

```css
/* Css fix for Obsidian-banners[2.0.5-beta] appearance when using Minimal theme[7.4.6]
See discussion of issue: https://github.com/noatpad/obsidian-banners/issues/146
~ NetSlayerUK
*/

body.minimal-theme .obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
	width: calc(100% + 2 * var(--size-4-12)); 
	margin: calc(-1 * var(--size-4-2)) calc(-1 * var(--size-4-12));
	margin-bottom: var(--size-4-2);
}

body.minimal-theme .banner-header.with-banner {
    padding: 0 var(--size-4-12);
}
```

Which puts things back in order for minimal theme users ^^

![image](https://github.com/noatpad/obsidian-banners/assets/14405930/4275d1cf-b53d-4c11-a0d0-1f03994dd75b)

**Comment by simonfossom** [comment]
nice one! 

BTW there's still a problem with top in focus mode. it needs stg like this or some other fix

```CSS
.view-content > .markdown-source-view.mod-cm6 > .cm-editor > .cm-scroller {
    padding: 0; 
}
```

**Comment by DudeThatsErin** [comment]
These seem to only work in reading view. Anyone know how to fix minimal for live preview mode?
I only use LP mode.

**Comment by simonfossom** [comment]
I am using also only live preview. It works fine for me. Check it is in conflict with your theme or some plugin.

**Comment by DudeThatsErin** [comment]
Works now. Not sure what the difference was.

Just has rounded borders on the top and bottom via mobile.

Also, my margin's are messed up. I can't close or open headings on mobile and on the desktop everything is hugging the sides. The width settings is default (88) in minimal theme settings.

![1B562EA1-6AA8-4476-A559-1444FC2346BB_4_5005_c](https://github.com/noatpad/obsidian-banners/assets/2681022/94d96a78-8b53-422b-b754-de1184f74aed)
![Screenshot 2024-03-18 at 3 17 56 PM](https://github.com/noatpad/obsidian-banners/assets/2681022/0a03db95-f96e-49dd-bacc-606da5a3d057)

Current snippet:
```css
body.minimal-theme .obsidian-banner-wrapper.with-banner:not(.in-internal-embed) {
	width: calc(100% + 2 * var(--size-4-12)); 
	margin: calc(-1 * var(--size-4-2)) calc(-1 * var(--size-4-12));
	margin-bottom: var(--size-4-2);
}

body.minimal-theme .banner-header.with-banner {
    padding: 0 var(--size-4-12);
}
```
EDIT: This new CSS Snippet fixed it. BUT I still have rounded borders on mobile.
