### ISSUE TITLE
[2.0.5 beta] Missing cursor icon in tables

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [noatpad/obsidian-banners#165]
Hey team, 

Heads up on a bug in the latest beta. When moving within a table in Live Preview mode there is no cursor icon in empty table cells. 

![Obsidian_PQAuxGMrYA](https://github.com/noatpad/obsidian-banners/assets/96321415/e843ed6b-bb0a-4fc0-9109-605d4e81e890)

Have completed an isolation test with a fresh vault and confirmed this issue is coming from the latest beta of Banners.

**Comment by VertexMachine** [comment]
Workaround: css snippet:
```css
/* bugfix for disappearing caret in new obsidian tables */
.table-editor .table-cell-wrapper .cm-scroller {
  flex-direction: row;
}
```
Solution from [here](https://forum.obsidian.md/t/tables-no-cursor-when-selecting-a-cell/76839/)
