### ISSUE TITLE
Work in Live Preview

### ISSUE THREAD

**Issue by Graywaren** [noatpad/obsidian-banners#175]
Hi
I originally was using Pixel Banner, since there were a number of posts about this plugin no longer working, but PB hasss apparently have sold out to AI and I'm horrified. I based some things in my vault around the ability to have banners, so I really want to maintain that functionality, but don't want to continue using something involved with gen ai, so I installed this. It seems to work well, which is great and I absolutely love the modal for selecting an image for the banner! Unfortunately it seems to only be visible in reading view. Is there any way this can be made to work in live preview? It's pretty much the only mode I use. 

Would really love to see this plugin continue to be maintained with the options for showing in live preview and a customizable gap between banner and content.

**Comment by GoblinCwl** [comment]
same

**Comment by pkkid** [comment]
I just got this working a few minutes ago, so your mileage may vary. When Obsidian is in Live Preview mode, it still has the Reading View in the DOM, just with `display:none`. This CSS will make visible only the parts of the Reading View elements needed to get the banner visible while in Live Preview mode. I also had to move the scrollable element up to the .view-content container, so everything scrolls together. Hopefully that plays nice for others.

```css
/*-------------------------
 * Fix Obsidian Banners
 * Temporary workaround for github issue:
 * https://github.com/noatpad/obsidian-banners/issues/175
 *-------------------------*/
.view-content:has(.obsidian-banner) {
  /* Fix inline-title padding and position. */
  /* NOTE: I am not sure if these hard-coded offsets will work with all themes. */
  .inline-title { margin-top: calc(var(--banner-height) - 20px) !important; }
  .obsidian-banner-wrapper { margin-top:0px; }
  .obsidian-banner-spacer { display: none; }
  .obsidian-banner-spacer + .cm-fold-indicator { top: calc(var(--banner-height) + 62px) !important; }

  /* Fix Live Preview - THIS IS HACKY
  /* Walk down the DOM tree making only the parts of .markdown-reading-view visible
  /* that are needed to get the reading-view banner visible and layered on top of
  /* the .markdown-source-view. This also moves the scrollable component up to the
  /* the .view-content container, so everything scrolls together. */
  &:has(.is-live-preview):has(.markdown-reading-view[style*="display: none"]) {
    overflow: auto;
    position: relative;
    .markdown-source-view {
      height: auto !important;
      .cm-scroller {
        height: auto !important;
        overflow: hidden !important;
      }
    }
    .markdown-reading-view {
      display: block !important;
      overflow: hidden !important;
      position: absolute;
      top: 0px;
      height: var(--banner-height) !important;
      > * { display:none !important; }
    }
    .markdown-preview-view {
      display: block !important;
      height: 100%;
      overflow: hidden;
      scrollbar-gutter: auto !important;
      > * { display:none !important; }
    }
    .markdown-preview-sizer {
      display: block !important;
      > * { display:none !important; }
    }
    .obsidian-banner-wrapper {
      display: block !important;
    }
  }
}

```
