### ISSUE TITLE
[BUG]  banner display width in LP mode

### ISSUE THREAD

**Issue by Borber** [noatpad/obsidian-banners#44]
![image](https://user-images.githubusercontent.com/30563826/158930873-4e429fde-2d34-497a-8b4e-e0cbeb33a6fe.png)

version: 0.14.2

**Comment by NekoSensei06** [comment]
+1
I think it’s because of the new indentation lines option, there is a new position relative on a parent div so the banner can’t expend outside.

**Comment by MugenLee** [comment]
+1
@noatpad

**Comment by Obadiahcruz** [comment]
```css
.markdown-source-view.mod-cm6 .cm-line:not(.HyperMD-list-line) {
	position: inherit;
}

.markdown-source-view.mod-cm6 .cm-line .ig-tab::before {
    position: absolute;
}
```

use this one
