### ISSUE TITLE
Theme Compatibility

### ISSUE THREAD

**Issue by creativefibro** [noatpad/obsidian-banners#62]
There seems to be a problem with the Minimal theme in the first image in the edit mode all is fine, but when you switch to reading mode the banner squishes up and overlaps with the writing.
<img width="1240" alt="CleanShot 2022-06-30 at 4 25 30@2x" src="https://user-images.githubusercontent.com/39191327/176898133-c97ebc8e-945a-40c5-bd4f-fed825a7a3b8.png">
<img width="1234" alt="CleanShot 2022-06-30 at 4 26 02@2x" src="https://user-images.githubusercontent.com/39191327/176898144-65eb1483-151b-4af7-a91d-fcc7c6dc0cd7.png">
.

**Comment by MaximilianHeidenreich** [comment]
Same here. I am using the [Things Theme](https://github.com/colineckert/obsidian-things).
![Bildschirmfoto 2022-08-25 um 01 27 06](https://user-images.githubusercontent.com/73365945/186540876-61cf8e08-1778-4b48-8234-11a85fda743a.png)
![Bildschirmfoto 2022-08-25 um 01 27 52](https://user-images.githubusercontent.com/73365945/186540935-cce8e260-9e93-44e0-9071-339a7f385c93.png)

**Comment by MaximilianHeidenreich** [comment]
Found a quick and dirty way to fix it using the following custom CSS snippet:

```css
.obsidian-banner-wrapper {
    position: static !important; /* Full width banner, remove for banner with same size as note content */
    margin-top: unset !important;
    margin-bottom: calc(var(--banner-height) + 0px); /* Adjust spacing between banner & content as needed */
}
```

_Note: Have not tested it with icons yet, as I don't use them..._

Might create a Pull-Request for a real fix in the future. Until it is fixed, just create a `banner-readmode-fix.css` file inside `yourVaultDir/.obsidian/snippets` and enable it inside the Obsidian settings at the bottom of the `Appearance` category.
@creativefibro 

Preview:
![Bildschirmfoto 2022-08-25 um 01 43 55](https://user-images.githubusercontent.com/73365945/186543064-db08bf25-6276-483a-9746-f13679f92299.png)

**Comment by mjs271** [comment]
Thank you, @MaximilianHeidenreich! Was having the same problem and your snippet fixed it right up.

I'm using the [Obsidian Nord Enhanced](https://github.com/AidanGlickman/obsidian-nord-enhanced) theme, FWIW.

**Comment by TimNekk** [comment]
Snippet that works both on **Desktop** and **Android** _(not tested on iOS)_

```css
.mod-header:has(+ .obsidian-banner-wrapper) {
  margin-top: var(--banner-height);
  margin-bottom: calc(-1 * var(--banner-height));
}
```
