### ISSUE TITLE
First line number in gutter is off

### ISSUE THREAD

**Issue by CabbageCanFly** [noatpad/obsidian-banners#72]
![image](https://user-images.githubusercontent.com/13248421/185248243-64ccfcc0-0122-418c-a895-3c5a570f5636.png)

The first line number in the gutter of Editing View is not pushed down along with the other numbers in the gutter.

I fixed it in the pic that I shared with the following CSS.

```css
.ͼ1 .cm-lineNumbers .cm-gutterElement:nth-child(2) {
    display: flex;
    justify-content: flex-end;
    align-items: flex-end;
}
```

There might be a better way of doing this, but I just wanted to bring this up. 👀
