### ISSUE TITLE
A bug that the banner is above the title's layer, which happends on all my PCs with few Plugins.

### ISSUE THREAD

**Issue by FallingEpiphany** [noatpad/obsidian-banners#91]
![image](https://user-images.githubusercontent.com/123282147/216075590-ef2f778a-e50c-456b-8809-3644f7ea485f.png)

As shown in the picture above.↑
And all my files with Banner have the same problem.
Where does it come from?

(First using Github)

**Comment by oliviercarizzoni** [comment]
Duplicate of #86

**Comment by Marksdo** [comment]
i add below to obsidian.css to fix
----------------
.cm-def {
   display: none; 
}

.obsidian-banner-spacer {
    height: 20px;
}

.cm-foldPlaceholder {
    display: none;
}
------------------------

**Comment by twp248** [comment]
Same issuses here.

**Comment by DudeThatsErin** [comment]
I'm running into this as well.

**Comment by FallingEpiphany** [comment]
> Figured out a fix with CSS.
> 
> ```css
> .obsidian-banner-spacer {
>   height: 200px;
>   margin-bottom: 0;
>   z-index: 99999;
> }
> .inline-title {
>   z-index: 1;
>   position: absolute;
>   top: 240px;
> }
> 
> .cm-def {
>   display: none;
> }
> 
> .cm-foldPlaceholder {
>   display: none;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/2681022/229865562-23b222f4-19fc-483e-897a-8ac2fa461a67.png)


> i add below to snippets/obsidian.css to temp fix
> 
> .cm-def { display: none; }
> 
> .obsidian-banner-spacer { height: 20px; }
> 
> .cm-foldPlaceholder { display: none; }

These are really helpful, thanks, budy.

**Comment by FallingEpiphany** [comment]
> Figured out a fix with CSS.
> 
> ```css
> .obsidian-banner-spacer {
>   height: 200px;
>   margin-bottom: 0;
>   z-index: 99999;
> }
> .inline-title {
>   z-index: 1;
>   position: absolute;
>   top: 240px;
> }
> 
> .cm-def {
>   display: none;
> }
> 
> .cm-foldPlaceholder {
>   display: none;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/2681022/229865562-23b222f4-19fc-483e-897a-8ac2fa461a67.png)


> i add below to snippets/obsidian.css to temp fix
> 
> .cm-def { display: none; }
> 
> .obsidian-banner-spacer { height: 20px; }
> 
> .cm-foldPlaceholder { display: none; }

These are really helpful, thanks, budy.

**Comment by android272** [comment]
> Figured out a fix with CSS.
> 
> ```css
> .obsidian-banner-spacer {
>   height: 200px;
>   margin-bottom: 0;
>   z-index: 99999;
> }
> .inline-title {
>   z-index: 1;
>   position: absolute;
>   top: 240px;
> }
> 
> .cm-def {
>   display: none;
> }
> 
> .cm-foldPlaceholder {
>   display: none;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/2681022/229865562-23b222f4-19fc-483e-897a-8ac2fa461a67.png)

This put the title in the middle of the new properties section so I added the following to revert the changes when in live-privew mode.

```css
.is-live-preview .metadata-container {
  z-index: 1;
  top: 50px;
}

.is-live-preview .obsidian-banner-spacer {
  height: 300px;
  margin-bottom: 0;
  z-index: 99999;
}

.is-live-preview .inline-title {
  z-index: 1;
  position: absolute;
  top: 0px;
}
```

Doesn't fix banners not showing in live-preview but makes this fix usable in 1.4

**Comment by noatpad** [comment]
Just as a quick mention, I'm aware of the banners being rather broken ever since 1.4 (#108) and have been working on a v2 refactor to basically become compatible with the new changes. There's currently a beta prerelease out that you can use via BRAT if you'd like to test it out

**Comment by oliviercarizzoni** [comment]
Thanks for your contribution, however the time has past, sad to see that usage of this plugin has been drastically reduced just because of this

**Comment by TimNekk** [comment]
Snippet that works both on **Desktop** and **Android** _(not tested on iOS)_

```css
.mod-header:has(+ .obsidian-banner-wrapper) {
  margin-top: var(--banner-height);
  margin-bottom: calc(-1 * var(--banner-height));
}
```
