### ISSUE TITLE
Enhancement: Default banner option (for when a unique banner for the note has not been selected)

### ISSUE THREAD

**Issue by DryIce1** [noatpad/obsidian-banners#93]
For consistency across the vault, it would be lovely to have a default banner on all pages that don't have a banner, so that your notes have a more consistent feel. This would help with the inline titles issue, too.

Proposed solution:
- in the banners settings, toggle on/off a default banner, and paste URL or image link into a comment box.

example default banner would be the apple iphone beach wallpaper:

![image](https://user-images.githubusercontent.com/59501376/218383261-644b2188-b36c-48c1-ab59-e4c46503ebae.png)

**Comment by DryIce1** [comment]
using a `:not(.has-banner)` class it should work, but I don't know how to put it back into the banner-image class.

below i have put it into the inline-title and it shows, but it is far from acceptable.
```css
:not(.has-banner) .inline-title {
  background-image: url("https://i.imgur.com/ApDch6y.png");
  background-repeat: no-repeat, repeat;
}
```
![image](https://user-images.githubusercontent.com/59501376/218384829-4b400c63-e6cf-4994-be96-4757ab66b1c7.png)
